name: Testing remote workflow
on: workflow_call
jobs:
  run_this_bich:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy output information
        run: echo DUMMY_SECRET is $meow
        env:
          meow: ${{ secrets.DUMMY_SECRET }}
